apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pingdirectory-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pingdirectory # Use appropriate label for your deployment
