apiVersion: v2
name: ping-devops
description: Helm chart for deploying PingFederate and PingDirectory on GKE Autopilot
type: application
version: 0.1.0
appVersion: "12.0.0"

keywords:
  - pingidentity
  - pingfederate
  - pingdirectory
  - ciam
  - gke
  - autopilot

maintainers:
  - name: CIAM Team

dependencies: []
