# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-pf-admin
# spec:
#   type: ClusterIP
#   selector:
#     app: {{ .Release.Name }}-pf-admin
#   ports:
#     - port: 9999
#       targetPort: 9999

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-pf-engine
# spec:
#   type: ClusterIP
#   selector:
#     app: {{ .Release.Name }}-pf-engine
#   ports:
#     - port: 9031
#       targetPort: 9031

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ .Release.Name }}-pd-user
# spec:
#   clusterIP: None
#   selector:
#     app: {{ .Release.Name }}-pd-user
#   ports:
#     - port: 1389
#       targetPort: 1389
