pingfederate-admin:
  enabled: true

  replicaCount: 1

  image:
    repository: pingidentity/pingfederate
    tag: "12.0.0"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "3"
      memory: "6Gi"

  service:
    type: ClusterIP
    port: 9999

  persistence:
    enabled: true
    size: 40Gi

  env:
    SERVER_PROFILE_PATH: "server-profile"
    OPERATIONAL_MODE: "CLUSTERED_CONSOLE"

  autoscaling:
    enabled: false
