pingfederate-engine:
  enabled: true

  replicaCount: 2

  image:
    repository: pingidentity/pingfederate
    tag: "12.0.0"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "6Gi"

  service:
    type: ClusterIP
    port: 9031

  env:
env:
  SERVER_PROFILE_URL: "https://github.com/akmal-fowmila/ciam-ping-serverprofile.git"
  SERVER_PROFILE_PATH: "pingfederate"
  OPERATIONAL_MODE: "CLUSTERED"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

