pingfederate-engine:
  enabled: true

  replicaCount: 2

  image:
    repository: pingidentity/pingfederate
    tag: "12.0.0"
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: "1"
      memory: "4Gi"
    limits:
      cpu: "4"
      memory: "6Gi"

  service:
    type: ClusterIP
    port: 9031

  env:
    SERVER_PROFILE_PATH: "server-profile"
    OPERATIONAL_MODE: "CLUSTERED_ENGINE"

  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70
